FROM scratch
# Call 'make build-all' before building it
ADD _dist/linux-amd64/kansible /
# Variables are interpolated not by Docker but by kansible (they are transmitted literally)
CMD [ "/kansible", "pod", "$KANSIBLE_HOSTS", "$KANSIBLE_COMMAND" ]
